cns_project/cns_app/urls.py
from django.urls import path

from . import views
from .views import user_login, user_logout, user_signup

urlpatterns = [
    path('', views.base, name="base"),
    path('index/', views.index, name="index"),
    path('raw_material/', views.raw_material, name="raw_material"),
    path('raw_material_details/', views.raw_material_view, name="raw_material_view"),
    path('raw_material_update/<int:pk>', views.raw_material_update, name="rm_update"),
    path('confirm/<int:pk>', views.confirm, name="confirm"),
    path('delete_rm/<int:pk>', views.delete_raw_material_entry, name="delete_rm_entry"),
    path('raw_expense/', views.raw_expense, name="raw_expense"),
    path('raw_expense_add/', views.raw_expense_add, name="raw_expense_add"),


    path('add_production/', views.add_production, name="add_production"),
    path('view_productions/', views.view_production, name="view_production"),
    path('edit_production/<int:pk>', views.edit_production, name="edit_production"),
    path('update_production/<int:pk>', views.update_production, name="update_production"),
    path('delete_production/<int:pk>', views.delete_production, name="delete_production"),
    path('dashboard_page/', views.dashboard, name="dashboard"),
    path('view_invoices/', views.view_invoices, name="view_invoices"),
    path('add_invoice/', views.add_invoice, name="add_invoice"),
    path('my_page/', views.my_page, name="my_page"),
    path('add_customer/', views.add_customer, name="add_customer"),
    path('customer_list/', views.view_customer, name="check_customer"),
    path('check_invoice/<int:invoice_id>', views.view_invoice, name="check_invoice"),
    path('payment_history/<int:customer_id>', views.payment_history, name="payment_history"),

    path('payment/', views.payment, name="payment"),
    path('view_payment/', views.view_payment, name="view_payments"),

    path('login/', user_login, name='login'),
    path('logout/', user_logout, name='logout'),
    path('signup/', user_signup, name='signup'),

    path('get_customer_address/<int:customer_id>/', views.get_customer_address, name='get_customer_address'),

]

cns_project/cns_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('cns_admin/', admin.site.urls),
    path('', include("cns_app.urls")),

]

cns_project/cns_app/forms.py
import uuid

from django import forms
from .models import RawMaterialModel, ProductionModel, InvoiceModel, Customer, PaymentModel
from address.forms import AddressField
from localflavor.in_.forms import INStateSelect
from django.core.validators import MinValueValidator, MinLengthValidator, MaxLengthValidator


class IndexForm(forms.Form):
    name = forms.CharField()
    age = forms.IntegerField()


class RawMaterialForm(forms.ModelForm):
    rst_no = forms.IntegerField(min_value=0, required=True, error_messages={'required': 'RST is required field'})
    net_wt = forms.DecimalField(required=True, decimal_places=2,
                                error_messages={'required': 'Weight is required field'})

    rate = forms.DecimalField(
        required=True, decimal_places=2,
        widget=forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'required field'}),
        error_messages={'required': 'Rate is required field'}
    )
    kanta_rate = forms.DecimalField(decimal_places=2, max_digits=12, initial=100)
    paid_amount = forms.DecimalField(decimal_places=2, max_digits=12, required=True)




    class Meta:
        model = RawMaterialModel
        fields = "__all__"

class RawExpenseForm(forms.Form):
    from .environment import Environment
    env = Environment()
    type = forms.ChoiceField(choices=env.Raw_Expense_Choices, widget=forms.Select(attrs={'class': 'form-control'}))
    description = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    expense_amount = forms.DecimalField(decimal_places=2, max_digits=12, widget=forms.TextInput(attrs={'class': 'form-control'}))


class ProductionForm(forms.ModelForm):
    product_rst = forms.IntegerField(required=True, error_messages={'required': 'RST Field is required'})
    vehicle_no = forms.CharField(required=False, max_length=10)
    product_net_weight = forms.DecimalField(decimal_places=2, error_messages={'required': 'Weight Field is required'})

    class Meta:
        model = ProductionModel
        fields = "__all__"

    class Media:
        js = ('js/auto_capitalize.js',)


class LoginForm(forms.Form):
    username = forms.CharField(label='Username', max_length=100)
    password = forms.CharField(label='Password', widget=forms.PasswordInput)


class InvoiceForm(forms.Form):
    from .environment import Environment
    invoice_env = Environment()
    customer = forms.ModelChoiceField(queryset=Customer.objects.all(), required=True)
    invoice_number = forms.IntegerField()
    e_way_bill = forms.CharField(max_length=50)
    total = forms.DecimalField(decimal_places=2, widget=forms.TextInput(attrs={'readonly': 'readonly'}))
    gst = forms.IntegerField(initial=5)
    discount = forms.IntegerField(widget=forms.NumberInput(attrs={'class': 'form-control'}), required=False, initial=0)
    payment = forms.DecimalField(widget=forms.TextInput(attrs={'readonly': 'readonly'}))
    item45mm = forms.BooleanField(label='Item 1', required=False,
                                  widget=forms.CheckboxInput(attrs={'class': 'form-check-input'}))
    item90mm = forms.BooleanField(label='Item 2', required=False,
                                  widget=forms.CheckboxInput(attrs={'class': 'form-check-input'}))
    item_pencil = forms.BooleanField(label='Item 3', required=False,
                                     widget=forms.CheckboxInput(attrs={'class': 'form-check-input'}))

    quantity_item1 = forms.DecimalField(label='Quantity for Item 1', required=False,
                                        widget=forms.NumberInput(attrs={'class': 'form-control'}))
    price_item1 = forms.DecimalField(label='Price for Item 1', required=False,
                                     widget=forms.NumberInput(attrs={'class': 'form-control'}))

    quantity_item2 = forms.DecimalField(label='Quantity for Item 2', required=False,
                                        widget=forms.NumberInput(attrs={'class': 'form-control'}))
    price_item2 = forms.DecimalField(label='Price for Item 2', required=False,
                                     widget=forms.NumberInput(attrs={'class': 'form-control'}))

    quantity_item3 = forms.DecimalField(label='Quantity for Item 3', required=False,
                                        widget=forms.NumberInput(attrs={'class': 'form-control'}))
    price_item3 = forms.DecimalField(label='Price for Item 3', required=False,
                                     widget=forms.NumberInput(attrs={'class': 'form-control'}))
    item_type = forms.ChoiceField(choices=invoice_env.item_choices, required=True, initial='Biomass Briquettes Mustard Husk 90 mm')
    item_quantity = forms.DecimalField(label='Quantity for Item', required=True)
    item_rate = forms.DecimalField(label='Rate for Item', required=True)
    shipping_address = forms.CharField(max_length=50)
    shipping_state = forms.ChoiceField(choices=invoice_env.STATE_CHOICES, label="Shipping State")
    shipping_city = forms.CharField(max_length=20)
    shipping_zip_code = forms.IntegerField()
    driver_name = forms.CharField(max_length=20, initial='UNKNOWN', required=True)
    driver_number = forms.IntegerField(initial=1234567890, required=True)
    assigned_vehicle = forms.CharField(max_length=10, initial='UNKNOWN', required=True)
    paid_amount = forms.DecimalField(max_digits=12, decimal_places=2, initial=0, required=True)
    shipping_state_code = forms.CharField(max_length=3)
    shipping_gstin = forms.CharField(max_length=50)
    shipping_company_name = forms.CharField(max_length=50)
    shipping_contact_number = forms.CharField(max_length=50)

    def clean_e_way_bill(self):
        e_way_bill = self.cleaned_data.get('e_way_bill')
        if InvoiceModel.objects.filter(e_way_bill=e_way_bill).exists():
            raise forms.ValidationError("E-Way Bill already exists.")
        return e_way_bill

    def clean_invoice_number(self):
        invoice_number = self.cleaned_data.get('invoice_number')
        if InvoiceModel.objects.filter(invoice_number=invoice_number).exists():
            raise forms.ValidationError("Invoice Number already exists.")
        return invoice_number

class CustomerForm(forms.Form):
    from .environment import Environment
    state_env = Environment()
    customer_name = forms.CharField()
    customer_number = forms.CharField(max_length=50)
    customer_address = forms.CharField()
    customer_state = forms.ChoiceField(choices=state_env.STATE_CHOICES)
    customer_city = forms.CharField(max_length=20)
    zip_code = forms.IntegerField(label='ZIP Code')
    customer_gstin = forms.CharField(max_length=20, required=True)
    customer_state_code = forms.CharField(max_length=3)
    # payment_status = forms.ChoiceField(choices=[('pending', 'PENDING'), ('paid', 'PAID')])
    # payment_dues = forms.DecimalField()


class PaymentForm(forms.Form):
    p_method = (
        ('cash', 'cash'),
        ('online', 'online'),
    )
    p_status = (
        ('paid', 'paid'),
        ('pending', 'pending'),
    )
    customer = forms.ModelChoiceField(queryset=Customer.objects.all())
    payment_method = forms.ChoiceField(choices=p_method, label='payment method')
    payment_amount = forms.DecimalField()
    # payment_status = forms.ChoiceField(choices=p_status, label='Status')
    # payment_dues = forms.DecimalField(null=True, max_digits=12, editable=False, decimal_places=2)

cns_project/templates/add_customer.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% load static %}
{{ customer_form.media }}
{% block title %} Customer {% endblock %}
{% block content %}

    <div class="container mt-5">
        <div class="jumbotron">
            {% include 'message.html'%}
            <form class="form-group post-form" method="post" action="">
                {% csrf_token %}
                <label for="id_customer_name">Company Name:*</label>
                <input  class="form-control" type="text" id="id_customer_name" name="customer_name" value="{{ form.customer_name.value|default_if_none:'' }}" required>
                <label for="id_customer_number">Customer Number:*</label>
                <input type="number" class="form-control" id="id_customer_number" name="customer_number" value="{{ form.customer_number.value|default_if_none:'' }}" required>
                <label for="id_customer_address">Customer Address:*</label>
                <input type="text" class="form-control" id="id_customer_address" name="customer_address" value="{{ form.customer_address.value|default_if_none:'' }}" required>
                <label for="id_customer_state">Customer state:*</label>
                <select name="customer_state" id="id_customer_state"  class=" form-control form-select">
                    {% for customer_state, label in customer_form.customer_state.field.choices %}
                        <option value="{{customer_state}}">{{label}}</option>
                    {% endfor %}
                </select>
                <label for="id_customer_city">Customer City:*</label>
                <input type="text" class="form-control" id="id_customer_city" name="customer_city" value="{{ form.customer_city.value|default_if_none:'' }}" required>

                <label for="id_zip_code">Zip Code:*</label>
                <input type="number" class="form-control" id="id_zip_code" name="zip_code" value="{{ form.zip_code.value|default_if_none:'' }}" required>

                <label for="id_customer_gstin">GSTIN:*</label>
                <input type="text" class="form-control" id="id_customer_gstin" name="customer_gstin" value="{{ form.customer_gstin.value|default_if_none:'' }}" required>

                <label for="id_customer_state_code">State Code:*</label>
                <input type="text" class="form-control" id="id_customer_state_code" name="customer_state_code" value="{{ form.customer_state_code.value|default_if_none:'' }}" required>

                <br><button  type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
{% endblock %}

cns_project/templates/add_production.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{{ form.media }}
{% block title %}Add Production{% endblock %}
{% block content %}
    <div class="container form-group  mt-5">
        <div class="jumbotron  ">
            {% include 'message.html'%}
            <h1> Please fill details... </h1>
            <form action = "" method = "post" class="post-form">
                {% csrf_token %}
                <label for="id_product_rst">Product RST:</label>
                <input autofocus type="number" class="form-control" id="id_product_rst" name="product_rst" value="{{ form.product_rst.value|default_if_none:'' }}" required>

                <label for="id_vehicle_no">Vehicle Number:</label>
                <input type="text" class="form-control" id="id_vehicle_no" name="vehicle_no" value="{{ form.product_rst.value|default_if_none:'' }}" >

                <label for="id_production_nt_wt">Product Net Weight: (Kg)</label>
                <input type="{{ add_product.product_net_weight.input_type}}" class="form-control" id="id_production_nt_wt" name="product_net_weight" value="{{ form.product_rst.value|default_if_none:'' }}" placeholder="Weight in Kg" required>

                <br><button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>

{% endblock %}

cns_project/templates/customer_list.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap5 %}
{% block title %}Customers {% endblock %}
{% block content %}

    <div class="container">
        <h1 class="text-center">Customers</h1>
        <div class="jumbotron table-responsive text-start">
            {% include 'message.html'%}

            <input   class="search_input  mt-5" style="float:left;" type="text" id="searchInput" placeholder="Search by Customer id...">
            <table class="table text-nowrap" id="customer_list" >
                <thead>
                    <tr>
                        <th scope="col">Sr No.</th>
                        <th scope="col"> Name</th>
                        <th scope="col"> Number</th>
                        <th scope="col"> GSTIN</th>
                        <th scope="col"> Address</th>
                        <th scope="col"> State</th>
                        <th scope="col"> City</th>
                        <th scope="col">zip_code</th>
                        <th scope="col">Dues</th>
                        <th scope="col">Payment Status</th>
                        <th scope="col">Created at </th>
                        <th scope="col">Updated at </th>
                        {% if user.is_authenticated %}
                        <th scope="col">Action</th>
                        {% endif %}

                    </tr>
                </thead>

            {% for data in customer_list %}
                <tbody>
                    <tr>
                        <th scope="row">{{ forloop.counter }} </th>
                        <td id="pay_id">{{data.customer_name |safe}}</td>
                        <td>{{data.customer_number|safe}}</td>
                        <td>{{data.customer_gstin|safe}}</td>
                        <td>{{data.customer_address|safe}}</td>
                        <td>{{data.customer_state|safe}}</td>
                        <td>{{data.customer_city|safe}}</td>
                        <td>{{data.zip_code|safe}}</td>
                        <td>{{data.payment_dues|safe}} Rs</td>
                        <td>{{data.payment_status|safe}}</td>
                        <td>{{data.created_at |date:"d-m-y H:i:s A"|safe}}</td>
                        <td>{{data.updated_at |date:"d-m-y H:i:s A"|safe}}</td>
                        {% if user.is_authenticated %}
                        <td><a href="{% url 'payment_history' data.pk %}" class="btn"><i class="bi bi-folder2-open" title="Preview {{data}}"></i></a></td>
                        {% endif %}
                        <!--<td>{{data.payment_status}}</td>-->

<!--                        <td>{{data.payment_dues}}</td>-->
                        <!--<td>
                            <a href="{% url 'edit_production' data.id %}">
                                <button type="button">Edit</button>
                            </a>
                            <a href="{% url 'delete_production' data.id %}">
                                <button type="button">Delete</button>
                            </a>
                        </td>-->
                    </tr>

                  </tbody>
                {% endfor %}
            </table>

            <!--<button id="btn" >Total net weight</button>-->
        </div>
    </div>

<script>
    $(document).ready(function(){
        $("#searchInput").on("keyup", function() {
            var value = $(this).val().toLowerCase();
            $("#customer_list tbody tr").filter(function() {
                $(this).toggle($(this).find("#pay_id").text().toLowerCase().indexOf(value) > -1);
            });
        });
    });
</script>

{% endblock %}

cns_project/templates/message.html
<div class="container mt-3">
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endfor %}
    <script>
                    // Close the alert after 5 seconds (adjust the duration as needed)
                    $(document).ready(function() {
                        setTimeout(function() {
                            $(".alert").alert('close');
                        }, 3000);
                    });
    </script>
</div>

cns_project/templates/my_page.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% load static %}
{% block title %} Final Good {% endblock %}
{% block content %}

    <div class="container-fluid bg-light">
        <div class="row">
            <div class="col-2  bg-primary">
                <marque>Hello</marque>
            </div>
            <div class="col-10">
                world
            </div>
        </div>
    </div>



    {% include 'message.html' %}
{% endblock %}

cns_project/templates/raw_expenses.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap5 %}
{% load custom_filters %}
{% block title %}Customers {% endblock %}
{% block content %}
    <div class="container">
        <h1 class="text-center"><marquee direction="right">Raw Material Expenses</marquee></h1> <hr>
        <div class="d-flex justify-content-evenly align-items-center">
            <div class="card text-center bg-danger" style="width:100px; height:75px;overflow:auto;">
                <p>Total Price</p>
               <h5 class=" card-title" id="total_data"> {{expense_total}} </h5>
            </div>
            <div class="card text-center bg-primary" style="width:100px; height:75px;overflow:auto;">
                <p>Diesel</p>
               <h5 id="diesel_price" class=" card-title"> {{diesel_price}} </h5>
            </div>
            <div class="card text-center bg-warning" style="width:100px; height:75px;overflow:auto;">
                <p>Labour Price</p>
               <h5 id="labour_price" class=" card-title">{{labour_price}} </h5>
            </div>
            <div class="card text-center bg-success" style="width:100px; height:75px;overflow:auto;">
                <p>Tripal Price</p>
               <h5 id="tripal_price" class=" card-title"> {{tripal_price}} </h5>
            </div>
            <div class="card text-center bg-secondary" style="width:100px; height:75px;overflow:auto;">
                <p>Extra Price</p>
               <h5 id="extra_price" class=" card-title"> {{extra_price}} </h5>
            </div>

        </div>
        <div class="  my-5 d-flex justify-content-evenly ">
            <form class="form " method="post">
                {% csrf_token %}
                {{ raw_expense_form }}<br>
                <input type="button" class="btn btn-primary " value="Submit" id="save-expense">
            </form>

            <div class="table-responsive" style="overflow:scroll; height:250px;">
                <table class="table table-stripe table-hover">
                    <thead class=" sticky-top">
                        <tr class="">
                            <th scope="col">#</th>
                            <th>ID</th>
                            <th>Type</th>
                            <th>Description</th>
                            <th>Amount</th>
                            <th>Created</th>
                            <th>Updated</th>
                        </tr>
                    </thead>
                    <tbody id="tbody">
                        {% for data in expense_data %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td>{{ data.expense_id }}</td>
                                <td>{{ data.type }}</td>
                                <td>{{ data.description }}</td>
                                <td>{{ data.expense_amount |indian_currency_format }} &#8377;</td>
                                <td>{{data.created_at |date:"d-m-y H:i:s A"}}</td>
                                <td>{{data.updated_at |date:"d-m-y H:i:s A"}}</td>
                            </tr>
                        {% endfor %}

                    </tbody>
                </table>
            </div>
        </div>

<!--        <button id="generate_pdf">Generate PDF</button>-->
    </div>


<script>
    $(document).ready(function () {
        console.log("refresh");

        function update_data(){
            console.log("update");
        }
        function formatDate(date) {
            var year = date.getFullYear().toString().substr(-2);
            var month = (date.getMonth() + 1).toString().padStart(2, '0');
            var day = date.getDate().toString().padStart(2, '0');
            var hours = date.getHours().toString().padStart(2, '0');
            var minutes = date.getMinutes().toString().padStart(2, '0');
            var seconds = date.getSeconds().toString().padStart(2, '0');
            var ampm = date.getHours() >= 12 ? 'PM' : 'AM';

            return `${day}-${month}-${year} ${hours}:${minutes}:${seconds} ${ampm}`;
        }
        $("#save-expense").click(function () {
            console.log("clicked");
            var raw_expense_type = $("#id_type").val();
            var raw_expense_description = $("#id_description").val();
            var raw_expense_amount = $("#id_expense_amount").val();
            console.log(raw_expense_type);
            console.log(raw_expense_description);
            console.log(raw_expense_amount);
            diesel = "{{diesel_price}}";
            my_data = {type:raw_expense_type, description:raw_expense_description, expense_amount:raw_expense_amount}
            $.ajax({
                type: 'POST',
                url: '{% url 'raw_expense_add' %}',
                data: my_data,
                success: function(data) {
                    if (data.success) {
                        var expenseData = data.expense_data;
                        // Empty the table
                        $('.table tbody').empty();
                        for (var i = 0; i < expenseData.length; i++) {
                            // Convert created_at and updated_at to Date objects
                            var createdAt = new Date(expenseData[i].created_at);
                            var updatedAt = new Date(expenseData[i].updated_at);
                            // Format the dates
                            var createdAtFormatted = formatDate(createdAt);
                            var updatedAtFormatted = formatDate(updatedAt);
                            console.log(createdAtFormatted, updatedAtFormatted);
                            console.log(i+1, expenseData[i].expense_id);
                            $('.table tbody').append('<tr><td>' + (i+1) + '</td><td>' + expenseData[i].expense_id + '</td><td>' + expenseData[i].type + '</td><td>' + expenseData[i].description + '</td><td>' + expenseData[i].expense_amount + '</td><td>' + createdAtFormatted + '</td><td>' + updatedAtFormatted + '</td></tr>');
                            $("#total_data").text(data.expense_total);
                            $("#diesel_price").text(data.diesel_price);
                            $("#labour_price").text(data.labour_price);
                            $("#tripal_price").text(data.tripal_price);
                            $("#extra_price").text(data.extra_price);
                        }
                    } else {
                        console.error('Error saving data:', data.errors);
                    }
                },
                error: function(error) {
                    console.error('Error creating data:', error);
                }
            });

        });

        $("#generate_pdf").click(function () {
            /*var doc = new jsPDF();
            doc.autoTable({ html: '.table' });
            doc.save('table.pdf');*/
        });

    });
</script>
{% endblock %}

cns_project/templates/raw_material.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% block title %}Add Raw Material{% endblock %}

{% block content %}

    <div class="container form-group  mt-5" >
        <div class="jumbotron">
            {% include 'message.html' %}
            <h1>  Raw Material </h1>
            <form action = "" method = "post" class="post-form">
                {% csrf_token %}
                <label for="raw_material_rst"> RST:</label>
                <input type="number" class="form-control" id="raw_material_rst" name="rst_no" value="{{ form.rst_no.value|default_if_none:'' }}" placeholder="required positive Integer only" inputmode="numeric" autofocus  required>

                <label for="raw_material_rate">Rate(Rs):</label>
                <input type="{{raw_material_form.rate.input_type}}" class="form-control" id="raw_material_rate" name="rate" value="{{ form.net_wt.value|default_if_none:'' }}" placeholder="required field " inputmode="decimal" required>

                <label for="id_kanta_rate">Kanta Rate(Rs):</label>
                <input type="{{raw_material_form.kanta_rate.input_type}}" class="form-control" id="id_kanta_rate" name="kanta_rate" value="{{ raw_material_form.kanta_rate.value|default_if_none:'' }}" placeholder="required field" inputmode="decimal" required>

                <label for="raw_material_net_wt"> Net Weight:</label>
                <input type="{{ raw_material_form.net_wt.widget.input_type }}" class="form-control" id="raw_material_net_wt" name="net_wt" value="{{ form.rate.value|default_if_none:'' }}" placeholder="required field / [weight in quintal only]" inputmode="decimal" required>

                <label for="raw_material_total">Total Payment:</label>
                <input type="number" class="form-control" id="raw_material_total" name="total" value="{{ form.total.value|default_if_none:'' }}" readonly>

                <label for="id_paid_amount">Paid Amount:</label>
                <input type="{{ raw_material_form.paid_amount.widget.input_type }}ber" class="form-control" id="id_paid_amount" name="paid_amount" value="{{ form.paid_amount.value|default_if_none:'' }}" placeholder="Required field" inputmode="numeric" required>


                <br><button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>

<script>
    $(document).ready(function () {

        $("#raw_material_net_wt, #raw_material_rate #id_kanta_rate").on("input", function () {
        var raw_weight = parseFloat($("#raw_material_net_wt").val()) || 0;
        var raw_price = parseFloat($("#raw_material_rate").val()) || 0;
        var kanta_rate = parseFloat($("#id_kanta_rate").val()) || 100;

        var raw_total = (raw_weight * raw_price);
        $('#raw_material_total').val(raw_total.toFixed(2));
    });
    });
</script>
{% endblock %}

cns_project/templates/rm_update.html
{% extends 'base.html' %}
{% block title %}Update Raw Material{% endblock %}
{%load bootstrap5 %}

{% block content %}
    <div class="container">
        <div class="jumbotron text-center">
            {% include 'message.html'%}

            <form action="" method = "post" class="post-form">
                {% csrf_token %}
                <label for="raw_rst">RST NUMBER:</label><br>
                <input id="raw_rst" name="rst" type="text"  value="{{data.rst_no}}"><br><br>
                <label for="id_kanta_rate">Kanta Rate:</label><br>
                <input id="id_kanta_rate" name="kanta_rate" type="text" value="{{data.kanta_rate}}"><br><br>
                <label for="id_paid_amount">Paid Amount:</label><br>
                <input id="id_paid_amount" name="paid_amount" type="text" value="{{data.paid_amount}}"><br><br>

                <label for="id_created_at">Creation Date:</label><br>
                <input id="id_created_at" name="created_at" type="datetime-local" value="{{data.created_at|date:'Y-m-d\TH:i' }}"><br><br>

                <label for="raw-net_weight">NET WEIGHT:</label><br>
                <input id="raw-net_weight" name="net_wt" type="text"  value="{{data.net_wt}}"><br><br>
                <label for="raw_rate">RATE:</label><br>
                <input id="raw_rate" name="rate" type="text" value="{{data.rate}}"><br><br>
                <label for="raw_total">TOTAL:</label>
                <br> <input id="raw_total" name="total" type="text"  value="{{data.total}}" readonly><br><br>
                <input formaction="{% url 'confirm' data.pk %}" type="submit" value="Confirm">
                <input formaction="{% url 'raw_material_view' %}" type="submit" value="Cancel">
            </form>

        </div>
    </div>
    <script>
        $(document).ready(function () {

                $("#raw-net_weight, #raw_rate, #id_kanta_rate").on("input", function () {
                var raw_weight = parseFloat($("#raw-net_weight").val()) || 0;
                var raw_price = parseFloat($("#raw_rate").val()) || 0;
                var kanta_rate = parseFloat($("#id_kanta_rate").val()) || 100;
                var raw_total = (raw_weight * raw_price);
                $('#raw_total').val(raw_total.toFixed(2));
            });
        });
    </script>
{% endblock %}